### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by rcook** [ombocomp/listsafe#1]
Would you consider adding this to Stackage?

**Comment by jtapolczai** [comment]
Sure, I'd be happy to. I'll do it either tomorrow or on Friday.

**Comment by jtapolczai** [comment]
I made a pull request, but the build is failing on another page.

https://github.com/fpco/stackage/pull/2719

**Comment by rcook** [comment]
That's unfortunate. The failure seems to be unrelated to `listsafe`.

**Comment by jtapolczai** [comment]
It's been merged.
